#!/usr/bin/env bash

echo "=========== Building site"

wget http://solovyov.net/files/gostatic-64-linux -O gostatic -q
chmod +x gostatic
apt-get install -y node-uglify node-less

./gostatic $1/config
