#!/usr/bin/env bash

LATEST=$(curl -s https://api.github.com/repos/piranha/gostatic/releases | awk '/"name": / { gsub(/[\",]/, ""); print $2; exit }')
wget https://github.com/piranha/gostatic/releases/download/$LATEST/gostatic-64-linux -O gostatic -q
chmod +x gostatic
apt-get install -y node-uglify node-less

echo    "-----> Building site"
echo -n "       "

./gostatic $1/config
