#!/bin/sh

LATEST=$(curl -s https://api.github.com/repos/piranha/gostatic/releases | awk '/"name": / { gsub(/[\",]/, ""); print $2; exit }')
CRITERIA=${1}-${LATEST}

# exit if it's already downloaded
test -f $CRITERIA && exit 0

echo    " ---> Downloading gostatic ${LATEST}"
curl https://github.com/piranha/gostatic/releases/download/$LATEST/gostatic-64-linux -o $1 -q
chmod +x $1
touch $CRITERIA
