#!/bin/sh

if [ -z "$1" ]; then
    echo "$0 SLUG"
    exit 0
fi

NAME="$(dirname $0)/src/blog/$(date +%Y)/$1.md"
DATE="$(date +%Y-%m-%d)"

mkdir -p $(dirname "$NAME")

cat > $NAME <<EOF
title: 
date: $DATE
tags: 
----


EOF

emacsclient --no-wait +1:8 "$NAME"
