# https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event
on:
  repository_dispatch:
    types:
      - xapicms

jobs:
  build:
    runs-on: buildjet-2vcpu-ubuntu-2004
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download babashka
        run: |
          curl -sLO https://github.com/babashka/babashka/releases/download/v0.6.4/babashka-0.6.4-linux-amd64-static.tar.gz
          tar xf babashka-0.6.4-linux-amd64-static.tar.gz
      - name: Update incoming post
        env:
          TGTOKEN: ${{ secrets.TGTOKEN }}
        run: ./bb incoming.clj "${{ github.event.client_payload.url }}"
      - name: commit and push if changed
        run: ./commit-if-changed.sh
    
