# https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event
on:
  repository_dispatch:
    types:
      - xapicms

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download babashka
        run: |
          which bb && exit 0
          curl -sLO https://github.com/babashka/babashka/releases/download/v0.10.163/babashka-0.10.163-linux-amd64-static.tar.gz
          tar xf babashka-0.10.163-linux-amd64-static.tar.gz
      - name: Update incoming post
        env:
          TGTOKEN: ${{ secrets.TGTOKEN }}
          PATH: ${{ env.PATH }}:/usr/local/bin:.
        run: bb bin/incoming.clj "${{ github.event.client_payload.url }}" "${{ github.event.client_payload.msgid }}"
      - name: commit and push if changed
        run: bin/commit-if-changed.sh
    
